### ISSUE TITLE
Install breaks

### ISSUE THREAD

**Issue by tnyavdc** [ryanvanderpol/expo-analytics#1]
**Expo version**
20.0.0

**React Native version**
0.47.0 

**Error output in packager**
`jest-haste-map: @providesModule naming collision:
  Duplicate module name: RCTEventEmitter
  Paths: /Users/DaCosta/Documents/patches/node_modules/expo-analytics/node_modules/react-native/Libraries/EventEmitter/RCTEventEmitter.js collides with /Users/DaCosta/Documents/patches/node_modules/react-native/Libraries/EventEmitter/RCTEventEmitter.js`

the above goes on for every package that is a duplicate of the package found in react native libraries

**Error displayed on device** 
`Unable to resolve module AccessibilityInfo...`

**Comment by ryanvanderpol** [comment]
Hi @tnyavdc.  Thanks for reporting this.  I could easily reproduce this problem on a brand new project.  I've just pushed an update (`v1.0.5`) that should fix this issue.  Please give it a try.  You may need to clear out your `node_modules` directory first (`rm -rf node_modules && npm install`) and possibly clear the React Native cache for your app (`exp start -c`)
