### ISSUE TITLE
Unclear how to set up Events

### ISSUE THREAD

**Issue by Laurensdc** [ryanvanderpol/expo-analytics#10]
Can't seem to set up custom Events with this.
Do I need to link Firebase (doesn't seem to support React Native)?

**Comment by ryanvanderpol** [comment]
@Laurensdc check out the README here for instructions how to use custom events: https://github.com/ryanvanderpol/expo-analytics#events

No, you don't need to use Firebase.  Just use a regular Google Analytics account.

**Comment by Laurensdc** [comment]
@ryanvanderpol Doesn't seem to work for me, maybe the events don't show up immediately?

**Comment by ryanvanderpol** [comment]
you can try looking under "Realtime" (can't remember off the top of my heas if events show up there). The regular event reporting can take many hours to show up, in my experience.

**Comment by Laurensdc** [comment]
Thanks I'll give it a go and close this issue. Cheers!

**Comment by Laurensdc** [comment]
It took almost 48 hours for my Events to show up, but they did just work!
