### ISSUE TITLE
Load time?

### ISSUE THREAD

**Issue by rosendanew** [ryanvanderpol/expo-analytics#12]
I can't see any data passed regarding the performance of the app e.g behaviour -> site speed? average load time? and etc. 

Is it possible?

**Comment by ryanvanderpol** [comment]
@rosendanew What exactly are you hoping to measure with this?  Most react native app screens should "load" instantaneously, unless you are making calls to an external API to load data.  In those cases, you could pretty easily create "events" using this library to track how long each API call takes.
