### ISSUE TITLE
Works when testing, but not when published

### ISSUE THREAD

**Issue by SoPlayNice** [ryanvanderpol/expo-analytics#22]
Hi, wondering if you could give a bit of insight.

I've added the module (which seems great btw, and very simple to add) to two apps. When testing on my local simulator and then through the QR code on a phone through Expo, the live data was showing when in Analytics. Because of this I published. However, now when trying on my phone with the live version, I don't seem to bet getting any data into Analytics.

It also works when scanning the QR code on the published projects, for example - https://expo.io/@sjames/entrancearchitect

Any ideas?

Thanks again.

**Comment by elliotstokes** [comment]
Did you find a solution to this. I'm hitting a similar issue where I can see the requests in development but on a published build the requests are not made. Appears to be iOS only though.

**Comment by SoPlayNice** [comment]
Ok thanks, I will give that a go too.

**Comment by SoPlayNice** [comment]
Turns out as I had updated the SDK version for Expo, but not submitted it to the app stores again, it wasn't actually sending my update to the stores. Missed that I needed to do that. Analytics is working perfectly now. 

Thanks
