### ISSUE TITLE
Types missing when installing with yarn

### ISSUE THREAD

**Issue by SantiMA10** [ryanvanderpol/expo-analytics#32]
Maybe I'm doing something wrong but if I install the package with `yarn add expo-analytics` I don't get the TypeScript types, but if I installed it from the GitHub repo, `yarn add ryanvanderpol/expo-analytics`, everything works great.

Any idea why this is happening?  

P.S. Awesome work with the package!

**Comment by romain-faust** [comment]
This is due to the fact that the NPM version has not been updated for 1 year.
@ryanvanderpol can you publish the latest changes to NPM please ?

Thank you by advance

**Comment by SantiMA10** [comment]
Let me know when this new release happed to update our dependency 😊

**Comment by ryanvanderpol** [comment]
@SantiMA10 @romain-faust latest NPM version (1.0.8) is now published.  Thanks for your patience!
