### ISSUE TITLE
Expo SDK 33 import warnings

### ISSUE THREAD

**Issue by seanfmcd** [ryanvanderpol/expo-analytics#35]
From the Expo SDK 33 release blog:
> With SDK 33, we’re deprecating imports of most modules from the expo package. This means that in a future release, you won’t be able to write, for example, import { FileSystem } from 'expo';. Rather, you’ll need to install the individual packages for each module you use and import from them instead.

The line below in `analytics.js` is now printing out deprecation warnings which would be great to get rid of.
`import { Constants } from 'expo';`

The import will need to change to
`import * as Constants from 'expo-constants';`
but I'm not sure what else is involved.

**Comment by ryanvanderpol** [comment]
thanks for the report! Working through this now -- see PR #34

**Comment by ryanvanderpol** [comment]
@seanfmcd FYI this has been published to NPM as 1.0.9. Please let me know if you have any further problems!
