### ISSUE TITLE
Change expo to expo-constants

### ISSUE THREAD

**Issue by davidmanson** [ryanvanderpol/expo-analytics#36]
Hello and thank you for this library,

I'm updating my application to Expo SDK 33 and I got a message about the separate packages for Constants.

I would be very thankful if you can make a quick update changing this line : 
`import { Constants } from 'expo'`

by this : 
`import Constants from 'expo-constants'`

Thank you very much

**Comment by ryanvanderpol** [comment]
Hey, thanks for reporting this! We've already got a PR for this (#34). It needs one more tweak before I release it so stay tuned!

**Comment by davidmanson** [comment]
Thank you for this quick answer ! I'm glad the fix is on the way :)

**Comment by ryanvanderpol** [comment]
@davidmanson FYI this has been published to NPM as 1.0.9.  Please let me know if you have any further problems!

**Comment by davidmanson** [comment]
Thank you very much ! No more warning about expo-constants, great :)
