### ISSUE TITLE
analytics.hit(new PageHit(screenName)) registers but cant see page name

### ISSUE THREAD

**Issue by mtnptrsn** [ryanvanderpol/expo-analytics#4]
`analytics.hit(new PageHit(screenName))` registers new page view but the page name isn't set. This worked before. I can't say exactly when this stopped working, unfortunately. Did google change the Analytics Api?
 
Pic: 
![screen shot 2018-01-22 at 10 13 27](https://user-images.githubusercontent.com/684179/35213168-fc8eedb4-ff5c-11e7-85a1-7713bb4ebe84.png)

**Comment by ryanvanderpol** [comment]
Hey @mtnptrsn, thanks for reporting this.  I have a couple apps out that are using this library and I'm not seeing this behavior.  Can you confirm that you are using version `1.0.6` of this package?  

Can you also confirm how you are passing in `screenName`?  Is it a hardcoded string or is it coming from somewhere else?  At one point I was doing something like `new PageHit(this.constructuro.toString())` and had a similar behavior so we changed it to `new PageHit('HomeScreen`)` throughout the app and that resolved the problem.

**Comment by mtnptrsn** [comment]
Hi, @ryanvanderpol 

Yes, I am using expo-analytics ^1.0.6.
No it's not hardcoded, my method looks like this

```
    static trackScreenView(screenName) {
        // /*
        // | Ignore tracking the screen if it's "DrawerOpen" (opening the main menu)
        // */
        // if (screenName === 'DrawerOpen') {
        //     return false;
        // }

        /*
        | Sending stats to google's server
        */
        analytics.hit(new PageHit(screenName));
    }
```
I debugged this and I am sure a screen name gets passed in. This is done automatically with react-navigation. (`onNavigationStateChange={ GoogleAnalytics.onNavigationStateChange }`on my RootNavigator)

onNavigationStageChange looks like this:
```
static onNavigationStateChange(prevState, currentState) {
    const currentScreen = GoogleAnalytics.getCurrentRouteName(currentState);
    const prevScreen = GoogleAnalytics.getCurrentRouteName(prevState);

    if (prevScreen !== currentScreen) {
        GoogleAnalytics.trackScreenView(currentScreen);
    }
}
```

**Comment by ryanvanderpol** [comment]
@mtnptrsn thanks for this info.  it all looks like it should be fine. for example, here is what one of my apps is showing

```
https://www.google-analytics.com/collect?tid=UA-XXXXXXX-5&v=1&cid=7B26292D-D075-46B1-ADBF-B8CBB77BFCB5&dp=Dashboard&t=pageview&an=xxxxx&aid=xxxxxx&av=1.4.9&sr=375x667&&z=57267168
```

Looks pretty close to yours, but I would say there are a couple things I would investigate.  First of all, the app version number.  looks like yours is `0.0.2`.  I kind of remember GA wanting that in a very specific format (like maybe not liking things below 1.0.0?) . Also, your app name has a `.` in it; I wouldn't think that would be an issue, but you never know.

Try tweaking those things and see what happens.  GA is pretty finicky...

**Comment by mtnptrsn** [comment]
Found the issue! I was supposed to use ScreenHit instead of PageHit. I was using an app view and couldnt see the screen becuase of that. Thanks for your help 😄
