### ISSUE TITLE
Unable to resolve "@unimodules/core" from "node_modules/expo-analytics/node_modules/expo-constants/build/ExponentConstants.js"

### ISSUE THREAD

**Issue by pckz** [ryanvanderpol/expo-analytics#41]
I have an App detached and I can't do `expo start -c` because I get the following error:

> Unable to resolve "@unimodules/core" from "node_modules/expo-analytics/node_modules/expo-constants/build/ExponentConstants.js"

Thanks

**Comment by ryanvanderpol** [comment]
@pckz what version of the Expo SDK are you using?  If you're using < 33 then you should use v1.0.8 of this package. I believe the changes made in #35 are not backwards compatible with previous SDK versions.

If you're using SDK 33+ then this might be a different problem.

**Comment by pckz** [comment]
I solved that doing
`yarn add @unimodules/core` and 
` yarn add @unimodules/react-native-adapter`

thanks!

**Comment by pioner92** [comment]
> @unimodules/react-native-adapter

  Thank you !!!!!!!!!! 👍
