### ISSUE TITLE
SDK 31 getWebviewUserAgentAsync is not a function

### ISSUE THREAD

**Issue by pckz** [ryanvanderpol/expo-analytics#43]
Hello
I'm using Expo SDK 31 with this lib, and my app works well until if I use this lib with the basic code:

> const analytics = new Analytics('UA-XXXXXX-Y');
>   analytics.hit(new PageHit('Home'))
>     .then(() => console.log("success"))
>     .catch(e => console.log(e.message));

If I comment that lines the app works well.

What can I do to solve this? Thanks

![Simulator Screen Shot - iPhone 7 - 2019-07-09 at 11 20 33](https://user-images.githubusercontent.com/1050628/60901566-31473b00-a23c-11e9-8434-4d8a04b35433.png)

**Comment by erm1lov** [comment]
+ also stuck on this

**Comment by ryanvanderpol** [comment]
@pckz as @erm1lov suggested, try pinning your version of this package to 1.0.8.  Seems that Expo SDK 33 introduced some non-backwards compatible changes.

**Comment by pckz** [comment]
It worked with
`    "expo-analytics": "^1.0.8",`
Thanks @erm1lov && @ryanvanderpol !
