### ISSUE TITLE
Sunsetting the Google Analytics Services SDKs

### ISSUE THREAD

**Issue by teckel12** [ryanvanderpol/expo-analytics#47]
Google is deprecating analytics for mobile apps:

https://support.google.com/firebase/answer/9167112?hl=en

I'm currently using expo-analytics in an iOS and Android application so I'm a bit confused as to why people are still using expo-analytics when it appears it won't work in another 2 months.

Am I missing something?  Does expo-analytics not use the Google Analytics Services SDK?

Thanks!

**Comment by ryanvanderpol** [comment]
Hey @teckel12, good question.  `expo-analytics` does not use the Google Analytics iOS or Android SDKs.  Actually, what it uses, is the same Google Analytics tools that you'd use on a web site.  So, as far as I'm aware, the sunsetting of those native SDKs shouldn't affect this project. 

That said, this project was really meant as a stop-gap measure until a better (native) solution became available and for some reason that hasn't happened and this project has become pretty popular.  I actually gave up on Expo several years ago so I don't even use this package anymore, but I will continue to help keep it going as long as there are no better alternatives.

**Comment by teckel12** [comment]
Thanks!

**Comment by josermorales** [comment]
@ryanvanderpol Just started using expo and find it super useful. Any reason I should stay away from it? (noob here)

**Comment by teckel12** [comment]
@josermorales A little off-topic, but I can't send my expo project to the Apple store because Apple removed the ability from Xcode 11. How is anyone making iOS builds with Expo with Xcode 11?

**Comment by kalliub** [comment]
@teckel12 
I just sent an app to Apple Store and because of this changes I had to download XCode 10 from Apple's website. Application Loader still works on XCode 10 versions.

**Comment by kalliub** [comment]
@josermorales Some people doesn't like Expo because "it's not native", and they think a little out of control of some things. Well, particularly speaking, I love Expo too! It gives me a lot of features that makes my job lots easier, so no one ever gave me a really decent reason to stay away from it.
