### ISSUE TITLE
TypeError: Network request failed

### ISSUE THREAD

**Issue by dylancompanjen** [ryanvanderpol/expo-analytics#5]
My app is crashing when the Google Analytics fetch is failing.
Should .hit return a Promise so I can catch errors after sending a hit?

"TypeError: Network request failed"

**Comment by ryanvanderpol** [comment]
@dylancompanjen good idea.  I'm happy to accept a PR if you have some time to make that change.

**Comment by dylancompanjen** [comment]
@ryanvanderpol Sure, I finally had some time :).

**Comment by ryanvanderpol** [comment]
@dylancompanjen thanks for the PRs.  I've merged them in and released 1.0.7 to npm.
