### ISSUE TITLE
Google Analytics Sunsetting Analytics SDK

### ISSUE THREAD

**Issue by jeremyhicks** [ryanvanderpol/expo-analytics#53]
Hi,

Will the functionality of `expo-analytics` be affected by this [announcement from Google](https://support.google.com/firebase/answer/9167112?hl=en) about the end of GA for App properties and the push to use Firebase?

**Comment by wscotten** [comment]
Would like to know this as well.

**Comment by ryanvanderpol** [comment]
There was some discussion about this in #47.  It is my understanding that there will be no impact since we are not using the mobile SDK but using the web APIs.  eg. the way this package works is that it is no different than having Google Analytics embedded on your website.

**Comment by wscotten** [comment]
Perfect.  Thank you for the response!
