### ISSUE TITLE
Unhandled promise rejection: TypeError: _expoConstants.default.getWebiewUserAgentAsync

### ISSUE THREAD

**Issue by greenwombat** [ryanvanderpol/expo-analytics#54]
Hi there,

I'd love to get using expo-analytics but am having trouble getting started.

I use the following:

    "expo": "^33.0.0",
    "expo-analytics": "^1.0.12",
    "react": "16.8.3",
    "react-dom": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz",
    "react-native-web": "^0.11.7"

import { Analytics, PageHit } from "expo-analytics";  // "expo": "^33.0.0" . 
const analytics = new Analytics("UA-MYKEY-2");

But even without trying to send an event I get the following error:

> [Unhandled promise rejection: TypeError: _expoConstants.default.getWebiewUserAgentAsync is not a function. (In '_expoConstants.default.getWebiewUserAgentAsync()', '_expoConstants.default.getWebiewUserAgentAsync' is undefined)]
> - node_modules/expo-analytics/analytics.js:18:8 in <unknown>

Any suggestions would be really appreciated,

Thank you,
George

**Comment by coinfielddev** [comment]
getWebiewUserAgentAsync should be: getWebViewUserAgentAsync there is a missing V

**Comment by bashash** [comment]
getWebiewUserAgentAsync should be: getWebViewUserAgentAsync there is a missing V

**Comment by greenwombat** [comment]
You're right! It looks like a bug in analytics.js:

![image](https://user-images.githubusercontent.com/7425250/66698157-31694200-ed27-11e9-9127-d5eba3b47528.png)

Manually changing this in node_modules fixes the problem.

**Comment by greenwombat** [comment]
I've created a pull request with the fix - it'd be great to get it merged:

https://github.com/ryanvanderpol/expo-analytics/pull/55

Thanks,
George

**Comment by ryanvanderpol** [comment]
🤦🏼‍♂️ Looks like this came over yesterday in #45.  Thanks, @greenwombat for the PR!  I'll get that merged and released asap.
