### ISSUE TITLE
Constants.deviceId should be Constants.installationId

### ISSUE THREAD

**Issue by kevwang1** [ryanvanderpol/expo-analytics#57]
In analytics.js, the client ID is set as Constants.deviceId from Expo. But I don't think that's actually supported by Expo - it should be Constants.installationId. I believe deviceid is currently set to installationId, but it is undocumented. For future stability, deviceId should be changed to installationId.

Where clientId is set: https://github.com/ryanvanderpol/expo-analytics/blob/697565cb87e0d54ad6d492faa2c06786f7052f33/analytics.js#L34

**Comment by aiham** [comment]
@kevwang1 I use the library like this:

```js
import { Analytics } from 'expo-analytics';
import Constants from 'expo-constants';
import { PixelRatio, Dimensions } from 'react-native';

const width = PixelRatio.getPixelSizeForLayoutSize(Dimensions.get('window').width);
const height = PixelRatio.getPixelSizeForLayoutSize(Dimensions.get('window').height);

const analytics = new Analytics('UA-123456-1', {
  ds: 'app',
  cid: Constants.installationId,
  sr: `${width}x${height}`,
});
```

**Comment by murshudov** [comment]
Please give a look at [Expo Analytics Google](https://github.com/mediusoft/expo-analytics-google)

**Comment by aiham** [comment]
@murshudov You've just copied this project without attribution, and made it worse.

**Comment by ryanvanderpol** [comment]
This change is now live in `1.0.16`
