### ISSUE TITLE
Update Readme on How to Setup the GA Account

### ISSUE THREAD

**Issue by sr3d** [ryanvanderpol/expo-analytics#6]
Since I'm using Expo for my app, expo-analytics seems to be the best candidate without having to eject and link.  However, it's not clear on how to setup the GA property.  The readme should be a bit more detailed on how to create the GA account (website, or mobile app, etc.).

**Comment by ryanvanderpol** [comment]
@sr3d yup, this is a good point.  If you haven't figured it out yet, you just need to set it up as a website.  Google Analytics now makes all "mobile app" properties go through Firebase.

**Comment by harshmaur** [comment]
@ryanvanderpol I think google does not allow requests from any website url other than the one specified in the settings. 

If I have an app, what should be my website url?
