### ISSUE TITLE
Google Analytics Property setup for React Native App in managed expo

### ISSUE THREAD

**Issue by BillyCottrell** [ryanvanderpol/expo-analytics#61]
So I am making my Bachelor Thesis around analytics in React Native environment with managed expo by using 3 different analytics (GA, MS App Center Analytics, and this one), and i am wondering how you setup the property in Google Analytics.
When choosing web for the property you need to provide an url which I don't have since it is an app that's running locally.
Can i somehow provide an url that I have which isn't used or is there an other way to do this?
Because with the explanation from the readme i have no clue how it would work for apps (only for websites that are online).

**Comment by ryanvanderpol** [comment]
The URL shouldn't matter.  Generally, I enter the marketing site URL for the product (eg. if I were setting this up for the Strava app, I'd put in strava.com).

**Comment by BillyCottrell** [comment]
Okay that's good to know, does expo also support integrations with google tag manager or other google products?

**Comment by BillyCottrell** [comment]
I'll take that as a no i guess.
