### ISSUE TITLE
Not compatible with Expo SDK44

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [ryanvanderpol/expo-analytics#81]
It is not compatible anymore with Expo SDK44.
Getting the following error:

`TypeError: null is not an object (evaluating '_expoConstants.default.manifest.name')`

It was working before with Expo SDK43

**Comment by marcus-chr** [comment]
Getting same error. No update regarding this issue? Using Expo SDK 45.

**Comment by mariomurrent-softwaresolutions** [comment]
Im currently using my fork 

https://github.com/meecodebymariomurrent/expo-analytics

With the newest expo SDK

**Comment by mariomurrent-softwaresolutions** [comment]
This will anyway be obsolete from SDK 47 onwards i guess
